# Generated by Django 4.2.1 on 2023-06-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamolibro",
            name="fecha_devolucion",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="prestamolibro",
            name="fecha_prestamos",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="socio",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
