# Generated by Django 4.2.1 on 2023-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Biblioteca", "0002_alter_prestamolibro_fecha_devolucion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamolibro",
            name="fecha_devolucion",
            field=models.DateField(),
        ),
    ]
