# Generated by Django 4.2.1 on 2023-06-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='prestamolibro',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='prestamolibro',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='prestamolibro',
            name='socio',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='PrestamoLibro',
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
